name: Keep Workflows Enabled

on:
  workflow_dispatch:      # manual trigger
  schedule:
    - cron: '0 6 */30 * *'  # Every 30 days at 6:00

permissions:
  actions: write           # Allow enabling workflows via API

jobs:
  keep-workflows-enabled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7.0.1
        with:
          script: |
            const { owner, repo } = context.repo;
            const listResponse = await github.rest.actions.listRepoWorkflows({ owner, repo });
            for (const wf of listResponse.data.workflows) {
            await github.rest.actions.enableWorkflow({ owner, repo, workflow_id: wf.id });
            }
